-- Zalo Bot Platform integration
-- Maps a Zalo Bot conversation (chat_id) to a linked VNGMeet account and tracks
-- the conversation's currently-active chat thread. Account linking is done from
-- the Mini App: the bot hands the user a one-time pairing code, the user opens
-- the (already phone-authenticated) Mini App which POSTs the code to /api/bot/link.

-- One row per Zalo Bot conversation.
create table if not exists bot_links (
  chat_id text primary key,                       -- Zalo Bot chat.id
  from_id text,                                    -- Zalo Bot from.id (sender)
  display_name text,                               -- Zalo display name (best-effort)
  -- Linked VNG account (= JWT sub); null = chưa link. KHÔNG đặt FK tới auth.users:
  -- session Zalo dùng sub = auth_user_id NẾU đã link Microsoft, NGƯỢC LẠI fallback
  -- về user_profiles.id (không tồn tại trong auth.users) → FK sẽ vỡ. Giống cách
  -- auth_zalo/mint_zalo_session vốn chấp nhận cả hai loại id.
  auth_user_id uuid,
  claims jsonb not null default '{}'::jsonb,       -- minimal claims (sub/email/name/phone) để mint session JWT
  current_thread_id uuid references thread(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Vá install cũ (bảng đã tạo kèm FK auth.users): gỡ FK để không vỡ khi sub =
-- user_profiles.id (user chưa link Microsoft).
alter table bot_links drop constraint if exists bot_links_auth_user_id_fkey;

create index if not exists idx_bot_links_auth_user
  on bot_links (auth_user_id);

-- One-time pairing codes generated by the bot for an unlinked conversation.
create table if not exists bot_pairings (
  code text primary key,                           -- mã pairing nhúng vào deep-link Mini App
  chat_id text not null,                            -- conversation cần liên kết
  from_id text,
  expires_at timestamptz not null,                 -- hết hạn sau bot_pairing_ttl_seconds
  used_at timestamptz,                              -- null = chưa dùng
  created_at timestamptz not null default now()
);

create index if not exists idx_bot_pairings_chat
  on bot_pairings (chat_id);

-- Server-side only (accessed via service-role key from the backend). RLS on with
-- no policies => no anon/authenticated access, matching provider_tokens.
alter table bot_links enable row level security;
alter table bot_pairings enable row level security;
